[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  [functions."bulk-insert"]
    timeout = 26

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  autoLaunch = false
